services:
  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"

  # app:
  #   build: .
  #   container_name: dotnet-app
  #   depends_on:
  #     - redis
  #   environment:
  #     - ASPNETCORE_ENVIRONMENT=Development
  #   ports:
  #     - "8080:8080"

  # networks:
  #   backend:
  #     driver: bridge
  #   payment-processor:
  #     external: true
