services:
  nginx:
    image: nginx:latest
    restart: unless-stopped
    container_name: rinha-nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api1
      - api2
    ports:
      - "9999:9999"
    networks:
      - backend
      - payment-processor
    deploy:
      resources:
        limits:
          cpus: "0.1"
          memory: "40MB"

  api1: &api
    image: wiliansa/rinha-backend-2025:v1
    restart: unless-stopped
    hostname: api1
    environment:
      - APP_PORT=8080
      - REDIS_URL=redis:6379
      - PROCESSOR_DEFAULT_URL=http://payment-processor-default:8080
      - PROCESSOR_FALLBACK_URL=http://payment-processor-fallback:8080
      - INSTANCE_ID=API-1
      - WORKER_CONCURRENCY=16
    networks:
      - backend
      - payment-processor
    depends_on:
      redis:
        condition: service_healthy
    deploy:
      resources:
        limits:
          cpus: "0.65"
          memory: "110MB"

  api2:
    <<: *api
    hostname: api2
    environment:
      - APP_PORT=8080
      - REDIS_URL=redis:6379
      - PROCESSOR_DEFAULT_URL=http://payment-processor-default:8080
      - PROCESSOR_FALLBACK_URL=http://payment-processor-fallback:8080
      - INSTANCE_ID=API-2
      - WORKER_CONCURRENCY=16
    deploy:
      resources:
        limits:
          cpus: "0.65"
          memory: "110MB"

  redis:
    image: redis:latest
    restart: unless-stopped
    container_name: rinha-redis
    ports:
      - "6379:6379"
    networks:
      - backend
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 5
    deploy:
      resources:
        limits:
          cpus: "0.1"
          memory: "90MB"

networks:
  backend:
    driver: bridge
  payment-processor:
    external: true