@urlBase = http://localhost:5187

### RegisterPayment
POST {{urlBase}}/payments
Content-Type: application/json
{
    "correlationId": "4a7901b8-7d26-4d9d-aa19-4dc1c7cf60b3",
    "amount": 19.90
}

### GetPaymentsSummary
GET {{urlBase}}/payments-summary //?from=2025-07-11T19:30:56.000Z&to=2025-07-11T19:35:56.000Z
Accept: application/json
